### ISSUE TITLE
进入白苹果logo页面进度条到一半的位置就花屏重启了

### ISSUE THREAD

**Issue by egoistttt** [sqlsec/AsRock-Z490-Steel-Legend-i7-10700#2]
cpu：10700k
主板：华勤z490 钢铁传奇
bios设置和你一样
显卡：无
用的是hdmi线连显示器

**Comment by sqlsec** [comment]
HDMI 线的数据我还没有来得及提交 PR，我这几天来更新一下，默认 DP是免驱的

**Comment by Nerders** [comment]
> HDMI 线的数据我还没有来得及提交 PR，我这几天来更新一下，默认 DP是免驱的

大佬，Ventura还更新嘛
