### ISSUE TITLE
引导异常

### ISSUE THREAD

**Issue by Nerders** [sqlsec/AsRock-Z490-Steel-Legend-i7-10700#3]
重置了NV，替换了大佬的EFI，但是开机巨大苹果（没有改过HiDpi），随便按一下开机按钮就关机了疑似没有作用。
主机独显接口DP显示器接口HDMI，同样的主板BIOS已经按照说明修改过了，毫无头绪请指教。

**Comment by sqlsec** [comment]
目前看样子属于个例现象 属于玄学问题了 只能靠自己解决
